version: 2.1

jobs:
  build:
    docker:
      - image: 'cimg/go:1.18.4'
    steps:
      - checkout
      - run:
          name: Check GO version
          command: go version 
      - run:
          name: Running build 
          command: go build cmd/gtink && ls -l gtink
  docker-build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: building image
          command: docker build -t gtink .
      - run:
          name: Tagging & pushing to docker
          command: |
            # if [ "${CIRCLE_BRANCH}" == "main" ]; then
              docker login --username ${DOCKER_USER} --password ${DOCKER_PASS}
              IMG_TAG=$(date +%Y%m%d-%H%M%S)
              docker tag gtink:latest "${DOCKER_USER}/gtink:${IMG_TAG}"
              docker push "${DOCKER_USER}/gtink:${IMG_TAG}"
            # else
              # echo "Branch is \"${CIRCLE_BRANCH}\" hence not pushing to dockerhub"
            # fi


workflows:
  base-workflow:
    jobs:
      - build
      - docker-build:
          filters:
            branches:
              only:
                - main1
          requires:
          - build
